### ISSUE TITLE
Act on Multiple Selection

### ISSUE THREAD

**Issue by dotHTM** [ALLZ/hex-bin_system#1]
Simple as that, would be awesome.

**Comment by ALLZ** [comment]
Well, I think it can be made, when I've got time to update the code.

**Comment by ALLZ** [comment]
Done.

**Comment by dotHTM** [comment]
You're awesome!

**Comment by franklinrt** [comment]
What is the format for multiple section?

Example. I have 0098 0098 on a single line. If I select just one instance of 0098, it converts to 152. If I select both "0098 0098" I get the error message "0098 0098" isn't a hexadecimal number. I get the same error if I put them on separate lines.
