### ISSUE TITLE
Problem to initiate Sublime vinculate to Hex-Bin System Plugin

### ISSUE THREAD

**Issue by calbertoquilo** [ALLZ/hex-bin_system#3]
Hi AllZ,
My name is Carlos. I would tell you that exit a conflict with your last merge in Hex-Bin System plugin.
## Aceptar   

But in the keymap file can see this:

[
<<<<<<< HEAD
    {"keys": ["ctrl+d","ctrl+h"], "command": "dec_to_hex"},
    {"keys": ["ctrl+d","ctrl+b"], "command": "dec_to_bin"},
    {"keys": ["ctrl+b","ctrl+d"], "command": "bin_to_dec"},
    {"keys": ["ctrl+b","ctrl+h"], "command": "bin_to_hex"},
    {"keys": ["ctrl+h","ctrl+d"], "command": "hex_to_dec"},
#     {"keys": ["ctrl+h","ctrl+b"], "command": "hex_to_bin"}

```
{"keys": ["ctrl+d","ctrl+h"], "command": "dec_to_hex"},
{"keys": ["ctrl+d","ctrl+b"], "command": "dec_to_bin"},
{"keys": ["ctrl+b","ctrl+d"], "command": "bin_to_dec"},
```

  {"keys": ["ctrl+b","ctrl+h"], "command": "bin_to_hex"},
  {"keys": ["ctrl+h","ctrl+d"], "command": "hex_to_dec"},
    {"keys": ["ctrl+h","ctrl+b"], "command": "hex_to_bin"}

> > > > > > > 736565c4382dadd2d10eeb9626dae94fe68a70a3
> > > > > > > ]

Please ...let me know if you can solved this error....

Best Regards,

**Comment by ALLZ** [comment]
Thanks, just my careless mistake) Fixed!

**Comment by calbertoquilo** [comment]
Hi ALLZ, the problem continue, because when I try set sublime text 2 I cant convert a number dec to hex or dec to hex. In Selection the option is in gray state. And the commands not work ok. In my case I use sublime in Windows.

Best Regards.
![sublime](https://f.cloud.github.com/assets/6772519/2262908/0bad1bda-9e5f-11e3-8a19-a7e0e1d3c2c5.png)

**Comment by ALLZ** [comment]
Check it now, all must be OK.
Many thanks for your help, and of course for using this pile of code=)

**Comment by calbertoquilo** [comment]
Hi ALLZ,
Thanks to solved the bug. Let me say my suggest: It would be a good idea to add complement'1 and complement'2 functionality for binary numbers cases

Best Regards,

**Comment by ALLZ** [comment]
Carlos,
I think I can do that, maybe on the next few weekends.
